import { defineConfig } from "vite-plus"

export default defineConfig({
  lint: {
    ignorePatterns: [
      "**/node_modules/**",
      "**/.sanity/**",
      "**/.svelte-kit/**",
      "**/.vercel/**",
      "**/build/**",
      "**/dist/**",
      ".agents/**",
      ".claude/skills/**",
      "apps/web/static/resources/vibecoding-demo/agent-sessions/**",
      "apps/web/static/studio/**",
    ],
    jsPlugins: [{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" }],
    plugins: ["typescript", "import"],
    rules: { "vite-plus/prefer-vite-plus-imports": "error" },
    options: { typeAware: true, typeCheck: true },
    overrides: [
      {
        files: ["apps/studio/**/*.ts", "apps/studio/**/*.tsx"],
        plugins: ["typescript", "import", "react"],
      },
      {
        files: ["**/*.test.ts", "**/*.test.mjs"],
        plugins: ["typescript", "import", "vitest"],
      },
    ],
  },
  fmt: {
    semi: false,
    printWidth: 80,
    sortPackageJson: false,
    sortTailwindcss: true,
    svelte: true,
    ignorePatterns: [
      "**/node_modules/**",
      "**/.sanity/**",
      "**/.svelte-kit/**",
      "**/.vercel/**",
      "**/build/**",
      "**/dist/**",
      ".agents/**",
      ".claude/skills/**",
      "apps/web/static/resources/vibecoding-demo/agent-sessions/**",
      "apps/web/static/studio/**",
      "**/bun.lock",
      "**/bun.lockb",
      "**/package-lock.json",
      "**/pnpm-lock.yaml",
      "**/yarn.lock",
    ],
  },
  run: {
    cache: {
      scripts: false,
      tasks: true,
    },
    tasks: {
      "generate:paraglide": {
        command: "node ./scripts/compile-paraglide.mjs",
        cwd: "apps/web",
        cache: true,
        input: [
          "package.json",
          "pnpm-lock.yaml",
          "vite.config.ts",
          "apps/web/package.json",
          "apps/web/paraglide.config.js",
          "apps/web/project.inlang/**",
          "apps/web/messages/**",
          "apps/web/scripts/compile-paraglide.mjs",
        ],
        output: [
          {
            pattern: "apps/web/src/lib/paraglide/**",
            base: "workspace",
          },
        ],
      },
      "sync:web": {
        command: "./node_modules/.bin/svelte-kit sync",
        cwd: "apps/web",
        cache: true,
        dependsOn: ["generate:paraglide"],
        input: [
          "package.json",
          "pnpm-lock.yaml",
          "vite.config.ts",
          "apps/web/package.json",
          "apps/web/src/**",
          "!apps/web/src/lib/paraglide/**",
          "apps/web/svelte.config.js",
          "apps/web/tsconfig.json",
          "apps/web/vite.config.ts",
        ],
        output: [{ pattern: "apps/web/.svelte-kit/**", base: "workspace" }],
      },
      "check:tooling": {
        command: "vp check",
        cache: true,
        dependsOn: ["sync:web"],
      },
      "check:svelte": {
        command: "./node_modules/.bin/svelte-check --tsconfig ./tsconfig.json",
        cwd: "apps/web",
        cache: true,
        dependsOn: ["sync:web"],
        input: [
          "package.json",
          "pnpm-lock.yaml",
          "vite.config.ts",
          "apps/web/package.json",
          "apps/web/paraglide.config.js",
          "apps/web/project.inlang/**",
          "apps/web/messages/**",
          "apps/web/scripts/compile-paraglide.mjs",
          "apps/web/src/**",
          "!apps/web/src/lib/paraglide/**",
          "apps/web/svelte.config.js",
          "apps/web/tsconfig.json",
          "apps/web/vite.config.ts",
        ],
        output: [],
      },
      "test:unit": {
        command: "vp test run",
        cwd: "apps/web",
        cache: true,
        dependsOn: ["sync:web"],
        input: [
          "package.json",
          "pnpm-lock.yaml",
          "vite.config.ts",
          "apps/web/package.json",
          "apps/web/paraglide.config.js",
          "apps/web/project.inlang/**",
          "apps/web/messages/**",
          "apps/web/scripts/**",
          "apps/web/src/**",
          "!apps/web/src/lib/paraglide/**",
          "apps/web/svelte.config.js",
          "apps/web/tsconfig.json",
          "apps/web/vite.config.ts",
        ],
        output: [],
      },
      "test:seo": {
        command: "node ./scripts/seo-audit.mjs build",
        cwd: "apps/web",
        cache: true,
        dependsOn: ["build"],
        input: [
          "package.json",
          "pnpm-lock.yaml",
          "vite.config.ts",
          "apps/web/package.json",
          "apps/web/scripts/seo-audit.mjs",
          "apps/web/vercel.json",
          "apps/web/.svelte-kit/output/client/**",
          "apps/web/.vercel/output/**",
        ],
        output: [],
      },
      "seo:live": {
        command: "node ./scripts/seo-audit.mjs live",
        cwd: "apps/web",
        cache: false,
      },
    },
  },
})
